stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: registry.dev.layanan.go.id/microtester/${CICD_GIT_REPO_NAME}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: registry.dev.layanan.go.id
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
