apiVersion: apps/v1
kind: Deployment
metadata:
  name: retwis-app
  namespace: asdf
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-asdf-retwis-app
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-asdf-retwis-app
    spec:
      containers:
      - image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-anri-${CICD_EXECUTION_SEQUENCE}
        name: retwis-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: webserver
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: pipeline-docker-registry
