apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}
  namespace: asdf
  labels:
    workload.user.cattle.io/workloadselector: deployment-asdf-${CICD_GIT_REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-asdf-${CICD_GIT_REPO_NAME}
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-asdf-${CICD_GIT_REPO_NAME}
    spec:
      imagePullSecrets:
        - name: ext-docker-registry
      containers:
        - name: dep-${CICD_GIT_REPO_NAME}
          image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
              name: webserver
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-${CICD_GIT_REPO_NAME}
  namespace: asdf
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:asdf:${CICD_GIT_REPO_NAME}"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
spec:
  clusterIP: None
  clusterIPs:
    - None
  ports:
    - name: webserver
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-asdf-${CICD_GIT_REPO_NAME}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: in-${CICD_GIT_REPO_NAME}
  namespace: asdf
spec:
  rules:
    - host: ooo.spbe.sangkuriang.co.id
      http:
        paths:
        - backend:
            service:
              name: svc-${CICD_GIT_REPO_NAME}
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
      - ooo.spbe.sangkuriang.co.id
      secretName: spbe-sangkuriang
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    field.cattle.io/displayName: hpa-${CICD_GIT_REPO_NAME}
  name: hpa-${CICD_GIT_REPO_NAME}
  namespace: asdf
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: ${CICD_GIT_REPO_NAME}
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
