apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}-app
  namespace: asdf
  labels:
    app: ${CICD_GIT_REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CICD_GIT_REPO_NAME}
  template:
    metadata:
      labels:
        app: ${CICD_GIT_REPO_NAME}
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: ${CICD_GIT_REPO_NAME}-app
          image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 80
              name: webserver
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-svc
  namespace: asdf
spec:
  selector:
    app: ${CICD_GIT_REPO_NAME}
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
