apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}-app
  namespace: asdf
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-asdf-${CICD_GIT_REPO_NAME}-app
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-asdf-${CICD_GIT_REPO_NAME}-app
    spec:
      containers:
      - image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: webserver
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: pipeline-docker-registry
---
apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-svc
  namespace: asdf
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-asdf-${CICD_GIT_REPO_NAME}-app
  ports:
    - name: webserver
      port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP
